[package]
name = "leptos-redirect-bug"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# [patch.crates-io]
# leptos = { path = "../leptos/leptos" }
# leptos_meta = { path = "../leptos/meta" }
# leptos_actix = { path = "../leptos/integrations/actix" }
# leptos_axum = { path = "../leptos/integrations/axum" }
# leptos_router = { path = "../leptos/router" }
# actix-web = { path = "../actix-web/actix-web" }
# actix-http = { path = "../actix-web/actix-http" }
# http = { path = "../http" }

[dependencies]
actix-files = { version = "0.6", optional = true }
actix-web = { version = "4", optional = true, features = ["macros"] }
console_error_panic_hook = "0.1"
http = { version = "1.0.0", optional = true }
leptos = { version = "0.7.0", features = ["nightly"] }
leptos_meta = { version = "0.7.0" }
leptos_actix = { version = "0.7.0", optional = true }
leptos_router = { version = "0.7.0" }
wasm-bindgen = "=0.2.95"
axum = { version = "0.7.9", optional = true }
leptos_axum = { version = "0.7.0", optional = true }
tower = { version = "0.5.1", optional = true }
tower-http = { version = "0.6.2", optional = true }
tokio = { version = "1.41.1", features = ["rt-multi-thread"], optional = true }

[features]
csr = [
  "leptos/csr",
]
hydrate = ["leptos/hydrate"]
ssr_actix = [
  "dep:actix-web",
  "dep:actix-files",
  "dep:leptos_actix",
  "leptos/ssr",
  "leptos/tracing",
  "leptos_meta/ssr",
  "leptos_meta/tracing",
  "leptos_router/ssr",
  "leptos_router/tracing",
]
ssr_axum = [
  "dep:axum",
  "dep:tower",
  "dep:tower-http",
  "dep:leptos_axum",
  "dep:tokio",
  "leptos/ssr",
  "leptos/tracing",
  "leptos_meta/ssr",
  "leptos_meta/tracing",
  "leptos_router/ssr",
  "leptos_router/tracing",
]

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[package.metadata.leptos]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle. Defaults to the crate name
output-name = "leptos-redirect-bug"
# The site root folder is where cargo-leptos generate all output. WARNING: all content of this folder will be erased on a rebuild. Use it in your server setup.
site-root = "target/site"
# The site-root relative folder where all compiled output (JS, WASM and CSS) is written
# Defaults to pkg
site-pkg-dir = "pkg"
# [Optional] The source CSS file. If it ends with .sass or .scss then it will be compiled by dart-sass into CSS. The CSS is optimized by Lightning CSS before being written to <site-root>/<site-pkg>/app.css
# style-file = "style/main.scss"
# Assets source dir. All files found here will be copied and synchronized to site-root.
# The assets-dir cannot have a sub directory with the same name/path as site-pkg-dir.
#
# Optional. Env: LEPTOS_ASSETS_DIR.
# assets-dir = "assets"
# The IP and port (ex: 127.0.0.1:3000) where the server serves the content. Use it in your server setup.
site-addr = "127.0.0.1:3000"
# The port to use for automatic reload monitoring
reload-port = 3001
# [Optional] Command to use when running end2end tests. It will run in the end2end dir.
#   [Windows] for non-WSL use "npx.cmd playwright test"
#   This binary name can be checked in Powershell with Get-Command npx
# end2end-cmd = "npx playwright test"
# end2end-dir = "end2end"
#  The browserlist query used for optimizing the CSS.
browserquery = "defaults"
# The environment Leptos will run in, usually either "DEV" or "PROD"
env = "DEV"
# The features to use when compiling the bin target
#
# Optional. Can be over-ridden with the command line parameter --bin-features
bin-features = ["ssr_actix"]

# If the --no-default-features flag should be used when compiling the bin target
#
# Optional. Defaults to false.
bin-default-features = false

# The features to use when compiling the lib target
#
# Optional. Can be over-ridden with the command line parameter --lib-features
lib-features = ["hydrate"]

# If the --no-default-features flag should be used when compiling the lib target
#
# Optional. Defaults to false.
lib-default-features = false

# The profile to use for the lib target when compiling for release
#
# Optional. Defaults to "release".
lib-profile-release = "wasm-release"
